Repository ezsystems/ezpublish-legacy, pull requests merged in 2019-01, with the labels that each got.

#1411 EZP-29957: Two XML blocks in the same Class in a different Categories will break second Online Editor
  extension/ezoe/design/standard/javascript/classes/dom/Selection.js
  extension/ezoe/design/standard/javascript/tiny_mce.js
  extension/ezoe/design/standard/javascript/tiny_mce_jquery.js
  extension/ezoe/design/standard/javascript/tiny_mce_jquery_src.js
  extension/ezoe/design/standard/javascript/tiny_mce_prototype.js
  extension/ezoe/design/standard/javascript/tiny_mce_prototype_src.js
  extension/ezoe/design/standard/javascript/tiny_mce_src.js
Labels: Bug, Ready for MERGE

#1386 EZP-29573: Legacy installer should allow utf8mb4 charset
  kernel/setup/steps/ezstep_installer.php
Labels: QA approved

#1416 EZP-29723: Content object attributes not set properly
  kernel/classes/datatypes/ezimage/ezimagetype.php
  kernel/content/attribute_edit.php
Labels: Ready for MERGE
